services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: web-crawler-backend
    depends_on:
      - mysql
    environment:
      DB_DSN: myuser:mypassword@tcp(mysql:3306)/crawler?charset=utf8mb4&parseTime=True&loc=Local
      DOCKERIZED: "true"
    ports:
      - "8080:8080"
    restart: unless-stopped
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web-crawler-frontend
    ports:
      - "8088:8088"
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8080
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crawler
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
