version: "3.8"
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: webcrawler-backend
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crawler
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
    container_name: backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    restart: always

volumes:
  mysql_data:
